### PR TITLE
Add CPU/Memory metrics as custom dimentions

### PR DESCRIPTION
**Pull request by xiaomi7732**
Thrown in a quick way to provide CPU/memory metrics when AI event happens.
A quick dirty solution for #78 .

E2E tested:
```
trce: Microsoft.ApplicationInsights.Kubernetes.KubernetesTelemetryInitializer[0]
      {"Timestamp":"2018-01-17T22:15:01.2764743+00:00","Sequence":null,"Context":
...

"Process.Memory":"104MB","Process.CPU(ms)":"1920"
...
```

### CODE REVIEW

**Comment by karolz-ms** [comment]
Have you considered reporting these as AI metrics, as opposed to custom telemetry properties?

**Comment by brahmnes** [comment]
I agree with Karol in that I don't think we should add these metrics on every single telemetry events. Looking at the requirement from https://github.com/Microsoft/ApplicationInsights-Kubernetes/issues/78, it can be probably be achieved by making sure the telemetry events, and the AI metrics, are both decorated with container name as properties, so queries can correlate them.

Having said that, I am not sure reporting CPU/memory metrics from this nuget is the best solution. At a minimum, I would prefer to make this configurable so it's not always collected automatically. An alternative would be to run an agent like telegraf and have it send data to AI.

**Comment by xiaomi7732** [comment]
@karolz-ms,
Thanks for the ask 👍. Yes, AI metrics is the first consideration but I chose to fall back to put these on the telemetry property intentionally.

Firstly, I think **it totally maps** for metrics to be tracked by AI metrics;

Then, there I see the **mismatch** for between AI events in AI.K8s and the profiling style AI metrics. At this point, I don't think it justified to implement a profiling logic in this library based on the ROI.

Third, this still addresses one scenario for those users that want to get basic metrics info and correlate it back to app events in one shot.

Based on those reasons, I think, why don't we just quickly throw in some data on the telemetry? At least, when the event happens, we can get a quick feeling on how is the CPU load and memory load looks like.

Does this address your question? Please let me know what's on your mind. :-)

**Comment by karolz-ms** [comment]
@xiaomi7732 it is a best practice to have a distinction between logs and metrics. They are often going through different pipelines and are handled by different backends. That said I understand this is somewhat of an experimental change, so let's experiment :)

**Pull request merged**
