### PR TITLE
Add CI to Github actions

### PR DESCRIPTION
**Pull request by xiaomi7732**
Part of #266. Unfortunately, I don't have a quick way to verify github actions before merging the change.

### CODE REVIEW

**Comment by xiaomi7732** [comment]
It looks like this would have caught the unit tests failing issue. Waiting for #267 to be merged first.

**Comment by xiaomi7732** [comment]
Interesting, the same unit test passed in Azure Pipeline but failed in github action CI build...

**Comment by xiaomi7732** [comment]
It looks like switching to windows-latest worked the problem around. It is weird because I couldn't repo the same issue on a local box of Ubuntu 22.04.

**Comment by xiaomi7732** [comment]
Also passes on ubuntu-22.04 in github action. I suspect there is an issue for the code specifically on 20.04.

**Review by karolz-ms — APPROVED** [review]

**Pull request merged**
